### ISSUE TITLE
Indexer deployment

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-subgraph#6]
- [ ] Create a render.com postgres database
- [ ] Get the IPFS pinning endpoint from Patrick
- [ ] Deploy the indexer docker 
- [ ] Configure DNS subgraph.opendollar.com
     - Playground
     - Query endpoint

**Comment by jahabeebs** [comment]
> * [ ]  Create a render.com postgres database
> 
>     * [ ]  Get the IPFS pinning endpoint from Patrick
> 
>     * [ ]  Deploy the indexer docker
> 
>     * [ ]  Configure DNS subgraph.opendollar.com
>       
>       * Playground
>       * Query endpoint

I saw in render that it will detect you have a dockerfile in the root so what do you think if I do the following:

1) change our docker-compose.yml to have .env variables for the network type (mainnet/arbitrum-sepolia), RPC URL, and postgres DB connection string, and IPFS pinning endpoint (which you can DM me)
2) after merging the changes above I should be able to create a .env in render and it should deploy the docker file successfully
3) set up dns

**Comment by pi0neerpat** [comment]
Sounds like a good plan. Please complete a tutorial on how to deploy using docker-compose, or directly from dockerfile if you'd rather that that approach.

**Comment by jahabeebs** [comment]
> Sounds like a good plan. Please complete a tutorial on how to deploy using docker-compose, or directly from dockerfile if you'd rather that that approach.

@pi0neerpat 

while trying to deploy I found that render doesn't have support for docker compose https://community.render.com/t/can-i-use-docker-compose/58/7

this makes things a bit trickier because we'll have to split all our docker compose services into dockerfiles (one for graph node service, one for IPFS service, one for postgreSQL service), build those images separately and then create a render.yaml to bring these together

**Comment by pi0neerpat** [comment]
Great work! My only question is whether our db will be persistent?

**Comment by jahabeebs** [comment]
> Great work! My only question is whether our db will be persistent? If so, you can close this issue

yes I've set up a 5GB disk for the deployment but we can raise the memory if this isn't enough
